apiVersion: batch/v1
kind: Job
metadata:
  name: crux-bench
spec:
  template:
    spec:
      containers:
      - name: crux-bench
        image: juxt/crux-bench
      restartPolicy: Never
  backoffLimit: 1
