apiVersion: apps/v1
kind: Deployment
metadata:
  name: crux-deployment
  labels:
    app: crux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crux
  template:
    metadata:
      labels:
        app: crux
        date: "1549289980"
    spec:
      containers:
      - name: crux
        image: 955308952094.dkr.ecr.eu-west-1.amazonaws.com/crux:latest
        ports:
        - containerPort: 3000

