kind: Service
apiVersion: v1
metadata:
  name: crux-http-service
  labels:
    app: crux-http-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: crux
