version: 0.0
os: linux

files:
  - source: environment
    destination: /var/lib/crux/
  - source: crux.jar
    destination: /srv/
  - source: crux.service
    destination: /usr/lib/systemd/system/

hooks:
  ApplicationStop:
    - location: stop.sh
      timeout: 300
  BeforeInstall:
    - location: before-install.sh
      timeout: 300
  AfterInstall:
    - location: after-install.sh
  ApplicationStart:
    - location: start.sh
      timeout: 300
  ValidateService:
    - location: check.sh
