version: '3.7'

services:
  website:
    build:
      context: .
      dockerfile: ../example/standalone_webservice/docker-images/development/Dockerfile

    restart: always
    command: lein repl :headless :host 0.0.0.0 :port 7889
    ports:
      - "7889:7889"
      - "8081:8080"

    working_dir: /app
    volumes:
      # Cache maven dependencies
      - "${HOME}/.m2:/root/.m2"
      # Mount the application source and target directories
      - ./:/app
